name: 'K8s Helm Multi-Deploy (no AWS)'
description: "Deploys all helm chart folders inside a 'deployment' folder in the project root."
inputs:
  kubeconfig:
    description: 'base64 encoded .kube/config'
    required: true
  image-tag:
    description: "The image tag to use in the deployments."
    required: true
  k8s-namespace:
    description: "Deployment namespace in kubernetes."
    required: true
  environment-slug:
    description: "Short name of deployment environment. Should be like 'dev', 'prod'. Set this if you have a values-<env>.yaml."
    required: false
  dry-run:
    description: "Skip the actual deployment and just show a diff."
    required: false
    default: false

branding:
  icon: box
  color: yellow
runs:
  using: docker
  image: docker://ghcr.io/atrakic/helm-multi-deploy:main
  env:
    HELM_IMAGE_TAG: ${{ inputs.image-tag }}
    HELM_K8S_NAMESPACE: ${{ inputs.k8s-namespace }}
    HELM_ENVIRONMENT_SLUG: ${{ inputs.environment-slug }}
    HELM_DRY_RUN: ${{ inputs.dry-run }}
