name: docker-ci
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'
    paths-ignore:
      - '**/README.md'

env:
  IMAGE_NAME: ci

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
        docker image ls ${{ env.IMAGE_NAME }}:$(date +%s)
        docker run -i --rm --entrypoint "bash" -v $(pwd):/deployment ${{ env.IMAGE_NAME }}:$(date +%s) -c "helm version"
        docker run -i --rm --entrypoint "bash" -v $(pwd):/deployment ${{ env.IMAGE_NAME }}:$(date +%s) -c "kubectl version"
